name: 'Set context variables'
description: 'An action to set context variables for workflows'

outputs:
  doBuild:
    description: "should build the project."
    value: ${{ steps.set-type.outputs.doBuild }}
  doRelease:
    description: "should release the project."
    value: ${{ steps.set-type.outputs.doRelease }}
  checkRelease:
    description: "should check the release is viable, but not release."
    value: ${{ steps.set-type.outputs.checkRelease }}

runs:
  using: 'composite'
  steps:
    - id: vars
      shell: bash
      run: |
        echo "Setting variables using event_data..."
        echo "isPush=${{ github.event_name == 'push' }}" >> $GITHUB_OUTPUT
        echo "isPR=${{ github.event_name == 'pull_request' && github.event.pull_request.draft == false }}" >> $GITHUB_OUTPUT
        echo "isMainBranch=${{ contains(github.event.ref, 'refs/heads/main') }}" >> $GITHUB_OUTPUT
        echo "isRelease=${{ github.event_name == 'release' }}" >> $GITHUB_OUTPUT
        echo "isTag=${{ github.event_name == 'create' && github.event.ref_type == 'tag' }}" >> $GITHUB_OUTPUT
        echo "isDraft=${{ github.event_name == 'pull_request' && github.event.pull_request.draft == true }}" >> $GITHUB_OUTPUT
        echo "isPreRelease=${{ github.event_name == 'release' && github.event.release.prerelease }}" >> $GITHUB_OUTPUT
        echo "forceBuild=${{ contains(github.event.pull_request.title, '[build]') }}" >> $GITHUB_OUTPUT
    - id: set-type
      shell: bash
      run: |
        echo "Setting pipeline type..."
        # Should build if it's a push to main, a non-draft PR, or a PR with '[build]' in the title
        forceBuild=${{ steps.vars.outputs.forceBuild }}
        isPR=${{ steps.vars.outputs.isPR }}
        isPush=${{ steps.vars.outputs.isPush }}
        isMainBranch=${{ steps.vars.outputs.isMainBranch }}
        if $forceBuild || $isPR || ($isPush && $isMainBranch); then
          echo "doBuild=true" >> $GITHUB_OUTPUT
        else
          echo "doBuild=false" >> $GITHUB_OUTPUT
        fi
        echo "doRelease=${{ steps.vars.outputs.isRelease }}" >> $GITHUB_OUTPUT
        echo "checkRelease=${{ steps.vars.outputs.isPreRelease }}" >> $GITHUB_OUTPUT
